language: node_js
node_js:
  - "6"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - cd Chapter 4
  - npm install -g gulp-cli
  - npm install -g gulp
  - npm install

script:
  - gulp build
